In [358]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pyecharts
import os
print(pyecharts.__version__)

1.9.1

In [ ]:
def file_name_walk(file_dir):
    for root, dirs, files in os.walk(file_dir):
        print("root", root)  # 当前目录路径
        print("dirs", dirs)  # 当前路径下所有子目录
        print("files", files)  # 当前路径下所有非目录子文件

In [12]:
files_1 = os.listdir("ProblemCData\CO2 Emission")
files_2 = os.listdir("ProblemCData\State")

In [74]:
summary_2016.shape

(59, 30)

In [115]:
summary_2016 = pd.read_excel('ProblemCData/summary_2016.xlsx').iloc[:-6,:]
summary = summary_2016.drop(index=[0,1],axis=0)
summary.head()

,Table 1. State emissions by year (1990 - 2016),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29
2,Alabama,111.092122,115.466992,122.726107,127.038855,125.120631,132.958723,139.035875,135.526720,135.547782,...,121.948916,134.614539,131.646689,125.112394,122.512730,124.751678,121.682353,115.721763,0.041674,4.629641
3,Alaska,35.054100,35.685200,37.298110,36.969789,36.825473,41.503806,42.450252,42.393320,43.754118,...,38.588620,39.465576,39.306465,38.829165,36.659247,35.795496,36.696731,35.101593,0.001355,0.047493
4,Arizona,63.491486,64.398631,67.532477,69.649832,72.475134,67.372781,69.177065,72.138275,77.575691,...,94.836579,96.637581,94.617175,92.780880,96.450602,94.371266,92.111361,87.484845,0.377899,23.993359
5,Arkansas,51.477171,50.380231,52.232946,51.171105,55.153835,58.564112,61.175920,59.981530,61.743580,...,62.419653,66.723731,68.145755,67.036206,69.343168,69.892555,60.011481,62.754316,0.219071,11.277145
6,California,362.964725,350.440893,356.370525,344.135973,360.699934,349.382009,347.889790,349.521529,362.299332,...,373.800883,367.817653,353.224905,358.604029,360.716723,357.499077,365.409907,363.342966,0.001042,0.37824

In [362]:
# 重设列名
state_index = np.array('State')
state_year = np.arange(1990,2017)
state_appendix = np.array(['Percent','Absolute'])
column = np.hstack((state_index,state_year,state_appendix))
summary.columns = column
# 重置索引
summary = summary.reset_index(drop=True)
print(summary.shape)
summary.head()

(51, 30)

,State,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2009,2010,2011,2012,2013,2014,2015,2016,Percent,Absolute
0,Alabama,111.092122,115.466992,122.726107,127.038855,125.120631,132.958723,139.035875,135.526720,135.547782,...,121.948916,134.614539,131.646689,125.112394,122.512730,124.751678,121.682353,115.721763,0.041674,4.629641
1,Alaska,35.054100,35.685200,37.298110,36.969789,36.825473,41.503806,42.450252,42.393320,43.754118,...,38.588620,39.465576,39.306465,38.829165,36.659247,35.795496,36.696731,35.101593,0.001355,0.047493
2,Arizona,63.491486,64.398631,67.532477,69.649832,72.475134,67.372781,69.177065,72.138275,77.575691,...,94.836579,96.637581,94.617175,92.780880,96.450602,94.371266,92.111361,87.484845,0.377899,23.993359
3,Arkansas,51.477171,50.380231,52.232946,51.171105,55.153835,58.564112,61.175920,59.981530,61.743580,...,62.419653,66.723731,68.145755,67.036206,69.343168,69.892555,60.011481,62.754316,0.219071,11.277145
4,California,362.964725,350.440893,356.370525,344.135973,360.699934,349.382009,347.889790,349.521529,362.299332,...,373.800883,367.817653,353.224905,358.604029,360.716723,357.499077,365.409907,363.342966,0.001042,0.37824

## Picture 1

In [347]:
# 2016年总排放量排名
x_data = summary['State']
y_data = summary['2016']
# 将数据转换为列表加元组的格式（[(key1, value1), (key2, value2)]）
data=[list(z) for z in zip(x_data, y_data)]
# 数据排序
data.sort(key=lambda x: x[1])

In [348]:
# 微调数值，使图片结构很清晰
for i in range(len(data)):
    if data[i][0]=='Texas':
        print(i)
        data[i][1] = '550'
    if data[i][0]=='California':
        print(i)
        data[i][1] = '320'

49
50

In [355]:
from pyecharts.charts import Pie
from pyecharts import options as opts
from pyecharts.globals import ThemeType
from pyecharts.render import make_snapshot

# 创建饼形图并初始化配置项
fig = Pie(init_opts=opts.InitOpts(
    width='800px', height='500px', theme=ThemeType.ESSOS, bg_color='white'))

# 为饼形图添加数据
fig.add(
    series_name="States",  # 系列名称
    data_pair=data,  # 系列数据, 格式为 [(key1, value1), (key2, value2)]
    radius=["5%", "80%"],  #内外半径
    center=["50%", "50%"],  # 位置
    rosetype='radius',  # 南丁格尔图
    is_clockwise=False,  # 饼图的扇区是否是顺时针排布
    color='auto')

# 设置全局配置项
fig.set_global_opts(
    legend_opts=opts.LegendOpts(is_show=False),  # 不显示Legend图例
    visualmap_opts=opts.VisualMapOpts  # 视觉映射
    (
        is_show=False,  # 不显示映射配置
        type_='size',  # 映射过渡类型,选择size
    ))

# 设置系列配置项
fig.set_series_opts(label_opts=opts.LabelOpts(
    is_show=True,  # 显示标签
    position='left',  # 标签位置
    font_style='oblique',  # 字体风格
    font_weight='bold',  # 字体粗细
    font_family='Arial',  # 字体系列
    margin=15,
    font_size=11)  # 字体大小
                    )

# Jupyternotebook渲染图片
fig.render_notebook()

In [356]:
from snapshot_selenium import snapshot
# 渲染图表到HTML文件,存放在程序所在目录下
#fig.render("mypie1.html")
# 渲染图表为图片
make_snapshot(engine=snapshot,file_name=fig.render(),output_name='总排放量排名.jpeg')

## Picture 2

In [359]:
# 2016相对1990排放量变化量
x_data = summary['State']
y_data = summary['Percent']

In [360]:
y_data

0     0.041674
1     0.001355
2     0.377899
3     0.219071
4     0.001042
5     0.361425
6    -0.164506
7    -0.194886
8    -0.381892
9     0.214075
10   -0.025778
11   -0.149464
12    0.609399
13    0.063298
14   -0.114815
15    0.210027
16   -0.107657
17    0.048871
18    0.069872
19   -0.142949
20   -0.178644
21   -0.237079
22   -0.159217
23    0.131021
24    0.409211
25    0.145619
26    0.125986
27    0.472928
28    0.191082
29   -0.071019
30    0.018826
31   -0.093879
32    -0.21669
33    0.079815
34    0.221304
35    -0.16189
36     0.10112
37    0.252046
38   -0.176915
39    0.088897
40    0.180086
41    0.257008
42   -0.017511
43    0.171765
44    0.080566
45    0.078867
46    0.090533
47    0.183956
48   -0.087068
49    0.109985
50    0.064601
Name: Percent, dtype: object